[project]
name = "baremalattes"
version = "0.1.0"
description = ""
authors = [
    {name = "gmcosta",email = "geu_costa@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "xmltodict (>=1.0.2,<2.0.0)",
    "psycopg (>=3.2.10,<4.0.0)",
    "pandas (>=2.3.3,<3.0.0)",
    "pydantic-settings (>=2.11.0,<3.0.0)",
    "zeep (>=4.3.2,<5.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "openpyxl (>=3.1.5,<4.0.0)"
]

[tool.poetry]
packages = [{include = "baremalattes", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
